### ISSUE TITLE
Release Lagom 1.5.2

### ISSUE THREAD

**Issue by dwijnand** [playframework/play-meta#112]
## Do the Release ([Full document](https://github.com/playframework/play-meta/blob/master/releasing/lagom.md))

* [x] [First-time Setup][]
* [x] [Review the Changes][]
* [x] [Before You Release][]
  * [x] [Triage issues][]
* [x] [Publish the Artifacts][]
* [x] [Update the Web Site][] <https://github.com/lagom/lagom.github.io/pull/201>
* [x] [Update the g8 templates and example projects][]
* [x] [Announce the Release][]
* [ ] [After-Release Cleanup][]

[First-time Setup]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#first-time-setup
[Review the Changes]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#review-the-changes
[Before You Release]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#before-you-release
[Triage issues]: https://github.com/issues?utf8=%E2%9C%93&q=label%3Atriage+org%3Alagom+archived%3Afalse+
[Publish the Artifacts]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#publish-the-artifacts
[Update the Web Site]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#update-the-web-site
[Update the g8 templates and example projects]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#update-the-g8-templates-and-example-projects
[Announce the Release]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#announce-the-release
[After-Release Cleanup]: https://github.com/playframework/play-meta/blob/master/releasing/lagom.md#after-release-cleanup

**Comment by dwijnand** [comment]
Failure running `deploy/release --project lagom --branch 1.5.x`

```
[error] SERVER ERROR: Internal Server Error url=https://oss.sonatype.org/service/local/staging/deploy/maven2/com/lightbend/lagom/maven-archetype-lagom-java/1.5.2/maven-archetype-lagom-java-1.5.2-sources.jar
[error] java.io.IOException: PUT operation to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/lightbend/lagom/maven-archetype-lagom-java/1.5.2/maven-archetype-lagom-java-1.5.2-sources.jar failed with status code 500: Internal Server Error
[error]         at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
[error]         at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:191)
[error]         at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error]         at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error]         at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:366)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:497)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:496)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:496)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2416)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2416)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (maven-java-archetype / publishSigned) java.io.IOException: PUT operation to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/lightbend/lagom/maven-archetype-lagom-java/1.5.2/maven-archetype-lagom-java-1.5.2-sources.jar failed with status code 500: Internal Server Error
[error] Total time: 2 s, completed Aug 30, 2019 9:00:31 AM
[error] java.lang.RuntimeException: Invalid programmatic input:
[error] Expected symbol
[error] Not a valid command: --
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] --failure--
[error]   ^
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at $1fa4b3d1a07d91da4ceb$.runCommand$1(build.sbt:123)
[error]         at $1fa4b3d1a07d91da4ceb$.$anonfun$releaseStepCommandAndRemaining$1(build.sbt:135)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:194)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:85)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:200)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid programmatic input:
[error] Expected symbol
[error] Not a valid command: --
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] --failure--
[error]   ^
[error] Use 'last' for the full log.
```

went into the repo `cd deploy/lagom`
and deleted the tag `git tag -d 1.5.2`
and reset the branch `git reset --hard HEAD^`
trying again

**Comment by dwijnand** [comment]
failed again, and this time I only have partial output:

```
# Nightly deploy script for Lagom documentation

set -e
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (broker-javadsl / publishSigned) java.lang.reflect.InvocationTargetException
[error] Total time: 8514 s, completed Aug 30, 2019 11:39:07 AM
[error] java.lang.RuntimeException: Invalid programmatic input:
[error] Expected symbol
[error] Not a valid command: --
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] --failure--
[error]   ^
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at $7c3e827e7b74c9e10fe8$.runCommand$1(build.sbt:123)
[error]         at $7c3e827e7b74c9e10fe8$.$anonfun$releaseStepCommandAndRemaining$1(build.sbt:135)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:194)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:85)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:200)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid programmatic input:
[error] Expected symbol
[error] Not a valid command: --
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] --failure--
[error]   ^
[error] Use 'last' for the full log.
```

going to try again

**Comment by dwijnand** [comment]
Looks like it published everything, but failed to close the sonatype repo, which (IIUC) Renato said happened to him too in the past:

```
[info] Reapplying settings...
[info] Set current project to lagom (in build file:/home/play/deploy/lagom/)
[info] lagom/lagom-sbt-plugin@1.5.2 was released
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.lightbend
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] Closing staging repository [comlightbend-1449] status:open, profile:com.lightbend(6723474620b7e0) description: Implicitly created (auto staging).
[info] Activity open started:2019-08-30T12:45:36.792Z, stopped:2019-08-30T12:46:29.361Z
[info] repositoryCreated: id:comlightbend-1449, user:jroper, ip:12.155.180.50
[info] Activity close started:2019-08-30T15:21:35.990Z, stopped:
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: profile-target-matching-staging
[info]     Passed: profile-target-matching-staging
[info]   Evaluate: pom-staging
[info]     Failed: pom-staging, failureMessage:Invalid POM: /com/lightbend/lagom/lagom-maven-plugin/1.5.2/lagom-maven-plugin-1.5.2.pom: SCM URL missing, Developer information missing
[info]   Evaluate: checksum-staging
[error] Failed to close the repository
[error] Activity close started:2019-08-30T15:21:35.990Z, stopped:
[error]     Failed: pom-staging, failureMessage:Invalid POM: /com/lightbend/lagom/lagom-maven-plugin/1.5.2/lagom-maven-plugin-1.5.2.pom: SCM URL missing, Developer information missing
[error] java.lang.Exception: Failed to close the repository
[error]         at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:762)
[error]         at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:854)
[error]         at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeRelease$1(Sonatype.scala:270)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbtrelease.ReleasePlugin$autoImport$.$anonfun$releaseStepCommand$2(ReleasePlugin.scala:93)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:194)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:85)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:200)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to close the repository
[error] Use 'last' for the full log.
```

**Comment by dwijnand** [comment]
Ah no it failed because https://github.com/lagom/lagom/pull/1973 wasn't backported

**Comment by dwijnand** [comment]
Tried to cherry-pick the change and force-republish maven-plugin (with override = true), but it looks like maybe Sonatype's staging repos only accept the first file?

Reset again and deleted the tag.

Will try again after https://github.com/lagom/lagom/pull/2214 is merged.

**Comment by dwijnand** [comment]
Wait... what?!  The output of `sonatypeRelease` showed it fail again for missing developer/scm tags... but looking at https://oss.sonatype.org/#stagingRepositories shows:

![image](https://user-images.githubusercontent.com/344610/64035915-d3ebae00-cb49-11e9-929a-fd02009d854d.png)

**Comment by dwijnand** [comment]
Updated a lagom-scala hello-world repo I had locally using sonatype releases and I'm getting:

```
[warn] 	module not found: com.lightbend.lagom#lagom-sbt-build-tool-support;1.5.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.lagom/lagom-sbt-build-tool-support/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.lagom/lagom-sbt-build-tool-support/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/dnw/.ivy2/local/com.lightbend.lagom/lagom-sbt-build-tool-support/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/lightbend/lagom/lagom-sbt-build-tool-support_2.12_1.0/1.5.2/lagom-sbt-build-tool-support-1.5.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/dnw/.sbt/preloaded/com.lightbend.lagom/lagom-sbt-build-tool-support/1.5.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/dnw/.sbt/preloaded/com/lightbend/lagom/lagom-sbt-build-tool-support_2.12_1.0/1.5.2/lagom-sbt-build-tool-support-1.5.2.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/lightbend/lagom/lagom-sbt-build-tool-support_2.12_1.0/1.5.2/lagom-sbt-build-tool-support-1.5.2.pom
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.lagom/lagom-sbt-plugin/scala_2.12/sbt_1.0/1.5.2/jars/lagom-sbt-plugin.jar ...
[info] 	[SUCCESSFUL ] com.lightbend.lagom#lagom-sbt-plugin;1.5.2!lagom-sbt-plugin.jar (1030ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lightbend.lagom#lagom-sbt-build-tool-support;1.5.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.lightbend.lagom:lagom-sbt-build-tool-support:1.5.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lightbend.lagom:lagom-sbt-build-tool-support:1.5.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		  +- com.lightbend.lagom:lagom-sbt-plugin:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (/d/lagom-scala-hello-world/project/plugins.sbt#L2-3)
[warn] 		  +- default:lagom-scala-hello-world-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
```

I think Sonatype releases is now dead, and just redirects to Maven Central.

So waiting on v1.5.2 to appear in https://repo1.maven.org/maven2/com/lightbend/lagom/lagom-sbt-build-tool-support_2.12_1.0/

Will review in a few hours.

**Comment by renatocaval** [comment]
Tried the released today after a few backports from master tp 1.5.x.

I got a few of error like this at the end of the release:

```
[info] Closed successfully
[info] Promoting staging repository [comlightbend-1451] status:closed, profile:com.lightbend(6723474620b7e0) description: Implicitly created (auto staging).
[info] Activity release started:2019-09-03T17:32:11.008Z, stopped:
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Passed: RepositoryWritePolicy
[info]     Passed: id:nx-internal-ruleset
[info]  copyItems: source:comlightbend-1451, target:releases
[info]      email: to:james@jazzy.id.au
[info] repositoryReleased: id:comlightbend-1451, target:releases
[info] Promoted successfully
[info] Dropping staging repository [comlightbend-1451] status:released, profile:com.lightbend(6723474620b7e0) description: Implicitly created (auto staging).
[info] Dropped successfully: comlightbend-1451
[info] Set current project to lagom (in build file:/home/play/deploy/lagom/)
[info] Setting version to '1.5.4-SNAPSHOT'.
[info] Reapplying settings...
[info] Set current project to lagom (in build file:/home/play/deploy/lagom/)
[info] [1.5.x 945fd01] Setting version to 1.5.4-SNAPSHOT
[info]  1 file changed, 1 insertion(+), 1 deletion(-)
[error] java.lang.RuntimeException: failed to release lagom/lagom-sbt-plugin@1.5.4-SNAPSHOT: {"message":"Version '1.5.4-SNAPSHOT' was not found"}
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at bintray.BintrayRepo.release(BintrayRepo.scala:77)
[error]         at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$25(BintrayPlugin.scala:120)
[error]         at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$25$adapted(BintrayPlugin.scala:117)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (bintrayRelease) failed to rel
```

But artifacts seem to be published.

**Comment by renatocaval** [comment]
Checked (manually 😠) and all artefacts were published for both 2.11 and 2.12 (note: this is 1.5.x, no 2.13 bins).

I will proceed with the release annoucements.

**Comment by renatocaval** [comment]
plugin is now fixed and we here is the reason why it was broken: https://github.com/lagom/lagom/pull/2228

**Comment by renatocaval** [comment]
Done!
